apiVersion: batch/v1
kind: Job
metadata:
  name: worker
  labels:
    {{- include "locust.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
spec:
  completions: {{ .Values.node.worker.replicas }}
  parallelism: {{ .Values.node.worker.replicas }}
  completionMode: Indexed
  ttlSecondsAfterFinished: 180
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "locust.selectorLabels" . | nindent 8 }}
        app.midokura.io/name: locust-worker
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: container-registry
      {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker-node
          image: "{{ .Values.node.image.repository }}:{{ .Values.node.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.node.image.pullPolicy }}
          command: ["locust"]
          env:
          - name: LOCUST_LOCUSTFILE
            value: {{ .Values.locust.fileName }}
          - name: LOCUST_MODE_WORKER
            value: "true"
          - name: LOCUST_MASTER_NODE_HOST
            value: master-service
          - name: RUN_ID
            value: {{ .Values.runId }}
          resources:
            {{- toYaml .Values.node.worker.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
