{
 "title": "Locust on Azure",
 "time": { "from": "2022-12-24T14:44:09.783Z", "to": "2022-12-24T15:37:49.360Z" },
 "templating": {
  "list": [
   {
    "name": "run_id",
    "label": "Run ID",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"locust\", tag: \"run_id\", start: v.timeRangeStart, stop: v.timeRangeStop)"
   },
   {
    "name": "percent",
    "label": "Percentile",
    "query": "90% : 90,  91% : 91,  92% : 92,  93% : 93,  94% : 94,  95% : 95,  96% : 96, 97% : 97,  98% : 98,  99% : 99, 100% : 100 "
   }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "${percent}%ile Delay Time (ms)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "getFieldValue = (tables=<-, field) => {\n    extract = tables\n        |> map(fn: (r) => ({ r with _value: r._value * ${percent} / 100 }))\n        |> findColumn(fn: (key) => key._field == field, column: \"_value\")\n\n    return extract[0] \n}\n\ntotal = from(bucket: \"eventhub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data\")\n  |> filter(fn: (r) => r[\"run_id\"] == \"$run_id\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> drop(columns: [\"uuid\", \"delay_ms\"])\n  |> sum()\n  |> getFieldValue(field: \"count\")\n\nfrom(bucket: \"eventhub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data\")\n  |> filter(fn: (r) => r[\"run_id\"] == \"$run_id\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> keep(columns: [\"delay_ms\", \"_value\"])\n  |> sum()\n  |> group()\n  |> map(fn: (r) => ({ r with delay_ms: int(v: r.delay_ms) }))\n  |> sort(columns: [\"delay_ms\"])\n  |> cumulativeSum(columns: [\"_value\"])\n  |> filter(fn: (r) => r._value < total)\n  |> last()\n  |> keep(columns: [\"delay_ms\"])"
    }
   ]
  },
  {
   "title": "Azure",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"eventhub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data\")\n  |> filter(fn: (r) => r[\"run_id\"] == \"$run_id\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> drop(columns: [\"uuid\", \"delay_ms\"])\n  |> sum()"
    }
   ]
  },
  {
   "title": "Outgoing Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"eventhub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data\")\n  |> filter(fn: (r) => r[\"run_id\"] == \"$run_id\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> drop(columns: [\"uuid\", \"delay_ms\"])\n  |> window(every: 1m)\n  |> sum()\n  |> group()\n  "
    }
   ]
  }
 ]
}