---
name: Continuous Delivery

on:
  push:
    branches:
    - main

concurrency: cd-${{ github.ref }}

jobs:
  continuous-integration:
    name: Continuous Integration
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  # continuous-delivery:
  #   name: Continuous Delivery
  #   runs-on: ubuntu-latest
  #   needs: continuous-integration
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3.1.0

  #   - name: Docker Login
  #     uses: docker/login-action@v1
  #     with:
  #       username: ${{ github.actor }}
  #       password: ${{ secrets.GITHUB_TOKEN }}
  #       registry: ghcr.io

  #   - name: Docker Build Locust
  #     uses: docker/build-push-action@v2
  #     with:
  #       file: mqtt_/Dockerfile
  #       tags: ghcr.io/locust-on-azure:latest
  #       push: true
  #       context: .

  #   - name: Docker Build Consumer
  #     uses: docker/build-push-action@v2
  #     with:
  #       file: consumer/Dockerfile
  #       tags: ghcr.io/eventhub-consumer:latest
  #       push: true
  #       context: .
