---
name: Continuous Integration

on: [workflow_call, pull_request]

concurrency: ci-${{ github.ref }}

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Run Pre-commit
      uses: pre-commit/action@v3.0.0
